name: upcrewpro
version: '1.0'
config-version: 2

profile: upcrewpro

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
