-- snowflake/sql/03_create_tables_and_pipe.sql
CREATE OR REPLACE TABLE UPCREWPRO.PUBLIC.STG_ORDERS (
  order_id STRING,
  customer_id STRING,
  amount NUMBER(10,2),
  order_ts TIMESTAMP_NTZ,
  ingestion_date DATE
);

CREATE OR REPLACE STAGE UPCREWPRO.PUBLIC.EXT_RAW_ORDERS
  URL='s3://upcrewpro-raw/orders'
  FILE_FORMAT = UPCREWPRO.PUBLIC.FILE_FORMAT_PARQUET
  -- CREDENTIALS=(AWS_KEY_ID='{{SNOWFLAKE_AWS_KEY}}' AWS_SECRET_KEY='{{SNOWFLAKE_AWS_SECRET}}')
  ;

CREATE OR REPLACE PIPE UPCREWPRO.PUBLIC.PIPE_LOAD_STG_ORDERS
  AUTO_INGEST = TRUE
  AS
  COPY INTO UPCREWPRO.PUBLIC.STG_ORDERS
  FROM @UPCREWPRO.PUBLIC.EXT_RAW_ORDERS
  FILE_FORMAT = (FORMAT_NAME = 'UPCREWPRO.PUBLIC.FILE_FORMAT_PARQUET')
  ON_ERROR = 'CONTINUE'
  PURGE = FALSE;
