-- snowflake/sql/04_grants.sql
GRANT USAGE ON DATABASE UPCREWPRO TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA UPCREWPRO.PUBLIC TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA UPCREWPRO.PUBLIC TO ROLE PUBLIC;
